FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY welcome_service.py .
COPY templates ./templates

CMD ["python", "welcome_service.py"]