FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY validation_service.py .
COPY customers.json .
# COPY templates ./templates

CMD ["python", "validation_service.py"]